package libmansys.view;

import java.awt.Color;
import java.sql.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import libmansys.dao.BookDAO;
import libmansys.dao.UserDAO;
import libmansys.model.Book;
import libmansys.model.User;
import libmansys.utils.Helper;
import org.jdesktop.swingx.prompt.PromptSupport;

public class NewBook extends javax.swing.JFrame {

    private Connection conn;
    private BookDAO dao;
    private String currentUsername;
    private int selectedRow = 0;

    public NewBook() {

    }

    public NewBook(Connection conn, String userName) {
        initComponents();
        setLocationRelativeTo(null); // center window

        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Database connection is null!");
            return; // 
        }
        this.conn = conn;
        this.currentUsername = userName;
        this.dao = new BookDAO(conn);

        // Right-align Penalty money column (e.g., column index 7)
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        tblBook.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);

        // Center
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tblBook.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblBook.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        tblBook.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);

        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        txtBookID.setEnabled(false);
        tblBook.setDefaultEditor(Object.class, null);
        PromptSupport.setPrompt("Search by Title, Author, or Category...", txtSearch);
        PromptSupport.setForeground(Color.GRAY, txtSearch);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, txtSearch);

        //Load table data
        loadBookTable();

        // Add live search/filter
        Helper.addTableFilter(tblBook, txtSearch, 1, 2, 4);

        // Optional: auto-resize columns based on content
        Helper.autoResizeColumns(tblBook);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtYear = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPublisher = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cboCategory = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTitle = new javax.swing.JTextArea();
        btnHome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scpBook = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 231, 230));
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)), "Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(204, 0, 153))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Year Published");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Publisher");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Title");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Author");

        btnUpdate.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(234, 231, 230));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(234, 231, 230));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Category");

        btnDelete.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(234, 231, 230));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Price");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Book ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Quantity");

        txtPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrice.setText("0.0000");
        txtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPriceFocusLost(evt);
            }
        });

        cboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "IT / Computer", "Management & Business", "Hospitality & Tourism", "Education & Academia", "Law & Criminology", "Other" }));
        cboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoryActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtTitle.setColumns(20);
        txtTitle.setLineWrap(true);
        txtTitle.setRows(5);
        txtTitle.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtTitle);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtYear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPublisher, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAuthor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, 208, Short.MAX_VALUE)
                            .addComponent(txtBookID)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(19, 19, 19))
        );

        btnHome.setBackground(new java.awt.Color(0, 102, 102));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(234, 231, 230));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)), "Books Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(234, 231, 230))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(234, 231, 230));

        tblBook.setBackground(new java.awt.Color(0, 102, 102));
        tblBook.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblBook.setForeground(new java.awt.Color(234, 231, 230));
        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Title", "Author", "Publisher", "Category", "Year", "Quantity", "Price"
            }
        ));
        tblBook.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblBook.setAutoscrolls(false);
        tblBook.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBook.setFillsViewportHeight(true);
        tblBook.setRowHeight(25);
        tblBook.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBook.setShowGrid(true);
        tblBook.getTableHeader().setReorderingAllowed(false);
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookMouseClicked(evt);
            }
        });
        scpBook.setViewportView(tblBook);

        txtSearch.setToolTipText("");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(scpBook, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scpBook, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("CLEAR");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnHome)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadBookTable() {
        try {
            List<Book> books = dao.getAllBooks();

            DefaultTableModel bookTbl = (DefaultTableModel) tblBook.getModel();
            bookTbl.setRowCount(0);

            for (Book b : books) {
                Object[] row = {b.getBookId(), b.getTitle(), b.getAuthor(), b.getPublisher(),
                    b.getCategory(), b.getYear(), b.getQuantity(), b.getBookPrice()
                };
                bookTbl.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading books: " + e.getMessage());
        }
    }

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Helper.goBackToHome(this, conn, currentUsername);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void cboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCategoryActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {

            // Create a book object from form values  
            Book book = getBookFromFields();

            // Then pass it to Book DAO
            boolean isUpdated = dao.updateBook(book);

            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Book updated successfully!");
                loadBookTable();
                clearBookFields();
            } else {
                JOptionPane.showMessageDialog(this, "No changes were made.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMouseClicked
        selectBookRow();

        // If user clicked on an empty space (no valid row)
        int rowAtPoint = tblBook.rowAtPoint(evt.getPoint());
        if (rowAtPoint == -1) {
            tblBook.clearSelection();
            clearBookFields();
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            return;
        }

        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblBookMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblBook.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a book to delete.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this book?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            JPasswordField pwdField = new JPasswordField();
            int option = JOptionPane.showConfirmDialog(
                    this,
                    pwdField,
                    "Enter your password to confirm delete",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (option != JOptionPane.OK_OPTION) {
                return; // user canceled 
            }
            String enteredPassword = new String(pwdField.getPassword());

            try {
                // Step 2: Verify password in the database
                UserDAO userDao = new UserDAO(conn);
                User confirmUser = userDao.login(currentUsername, enteredPassword);

                if (confirmUser == null) {
                    JOptionPane.showMessageDialog(this, "Incorrect password. Delete cancelled.");
                    return;
                }

                int bookId = Integer.parseInt(txtBookID.getText());
                String title = txtTitle.getText();
                boolean isDeleted = dao.deleteBook(bookId);

                if (isDeleted) {
                    JOptionPane.showMessageDialog(this, "Book " + title + "  has been successfully deleted.",
                            "Success", JOptionPane.INFORMATION_MESSAGE);
                    //JOptionPane.showMessageDialog(this, "Book " + title + " deleted succesfully");
                    loadBookTable();
                    clearBookFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot delete this book. It is currently borrowed!",
                            "Warning", JOptionPane.WARNING_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error deleting book: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

        }

        clearBookFields();
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!validateBookFields()) {
            return;
        }
//
//        // Check if combo box is default
//        boolean comboDefault = cboCategory.getSelectedIndex() == 0; // or your default index
//
//        String priceText = txtPrice.getText().trim();
//        boolean priceInvalid = false;
//
//        try {
//            if (priceText.isEmpty()) {
//                throw new NumberFormatException("Empty input");
//            }
//
//            double price = Double.parseDouble(priceText);
//
//            // Reject zero or negative values
//            if (price <= 0.0) {
//                priceInvalid = true;
//            }
//        } catch (NumberFormatException e) {
//            priceInvalid = true; // Non-numeric input like letters or symbols
//        }
//
        //// Handle result
//        if (priceInvalid) {
//            txtPrice.setBackground(Color.PINK); // Highlight error
//            JOptionPane.showMessageDialog(this, "Price must be a valid amount.");
//            txtPrice.requestFocus();
//            return; // Stop further execution
//        } else {
//            txtPrice.setBackground(Color.WHITE); // Reset if valid
//        }
//
//        if (comboDefault || priceInvalid) {
//            String message = "The following fields are still at their default values:\n";
//            if (comboDefault) {
//                message += "- Category\n";
//            }
//            if (priceInvalid) {
//                message += "- Price\n";
//            }
//            message += "Do you want to continue?";
//
//            int option = JOptionPane.showConfirmDialog(
//                    this,
//                    message,
//                    "Warning",
//                    JOptionPane.YES_NO_OPTION,
//                    JOptionPane.WARNING_MESSAGE
//            );
//
//            if (option != JOptionPane.YES_OPTION) {
//                return; // user chose not to continue
//            }
//        }

        Book book = getBookFromFields();

        try {
            boolean isAdded = dao.addBook(book);

            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Book added successfully!");
                loadBookTable();
                clearBookFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add the book");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        clearBookFields();

        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusGained
        if (txtPrice.getText().equals("0.0000")) {
            txtPrice.setText("");
        }
    }//GEN-LAST:event_txtPriceFocusGained

    private void txtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPriceFocusLost
        String textPrice = txtPrice.getText().trim();

        if (txtPrice.getText().trim().isEmpty()) {
            txtPrice.setText("0.0000");
        } else {
            try {
                double value = Double.parseDouble(textPrice);

                // If whole number, format with 2 decimal places
                if (value == (int) value) {
                    txtPrice.setText(String.format("%.2f", value));
                } else {
                    // keep original decimal value, but optionally format consistently
                    txtPrice.setText(String.valueOf(value));
                }

            } catch (NumberFormatException e) {
                // Optional: handle invalid input
                txtPrice.setText("0.0000");
            }
        }
    }//GEN-LAST:event_txtPriceFocusLost

    //Private Helper methods
    private void selectBookRow() {
        selectedRow = tblBook.getSelectedRow();

        if (selectedRow != -1) {
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnAdd.setEnabled(false);

            txtBookID.setText(tblBook.getValueAt(selectedRow, 0).toString());
            txtTitle.setText(tblBook.getValueAt(selectedRow, 1).toString());
            txtAuthor.setText(tblBook.getValueAt(selectedRow, 2).toString());
            txtPublisher.setText(tblBook.getValueAt(selectedRow, 3).toString());
            cboCategory.setSelectedItem(tblBook.getValueAt(selectedRow, 4).toString());
            txtYear.setText(tblBook.getValueAt(selectedRow, 5).toString());
            txtQuantity.setText(tblBook.getValueAt(selectedRow, 6).toString());
            txtPrice.setText(tblBook.getValueAt(selectedRow, 7).toString());
        } else {
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            clearBookFields(); // optional — see below
        }
    }

    private void clearBookFields() {
        txtBookID.setText("");
        txtTitle.setText("");
        txtAuthor.setText("");
        txtPublisher.setText("");
        cboCategory.setSelectedIndex(0);
        txtYear.setText("");
        txtQuantity.setText("");
        txtPrice.setText("");
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnAdd.setEnabled(true);

        // Reset background colors
        txtTitle.setBackground(Color.WHITE);
        txtAuthor.setBackground(Color.WHITE);
        txtPublisher.setBackground(Color.WHITE);
        txtYear.setBackground(Color.WHITE);
        txtQuantity.setBackground(Color.WHITE);
        txtPrice.setBackground(Color.WHITE);
        cboCategory.setBackground(Color.WHITE);

        // Optionally, set focus to the first field
        txtTitle.requestFocus();
    }

    private Book getBookFromFields() {
        Book book = new Book();

        // If your Book has bookId (for update)
        if (!txtBookID.getText().isEmpty()) {
            book.setBookId(Integer.parseInt(txtBookID.getText()));
        }

        book.setTitle(txtTitle.getText());
        book.setAuthor(txtAuthor.getText());
        book.setPublisher(txtPublisher.getText());
        book.setCategory(cboCategory.getSelectedItem().toString());

        // Validate numeric fields
        try {
            book.setYear(Integer.parseInt(txtYear.getText()));
        } catch (NumberFormatException e) {
            book.setYear(0); // or handle properly
        }

        try {
            book.setQuantity(Integer.parseInt(txtQuantity.getText()));
        } catch (NumberFormatException e) {
            book.setQuantity(0);
        }

        try {
            book.setBookPrice(Double.parseDouble(txtPrice.getText()));
        } catch (NumberFormatException e) {
            book.setBookPrice(0.0);
        }

        return book;
    }

    private boolean validateBookFields() {
        StringBuilder errors = new StringBuilder();
        int currentYear = java.time.Year.now().getValue();

        // --- Text fields ---
        if (txtTitle.getText().trim().isEmpty()) {
            errors.append("• Title is required.\n");
            txtTitle.setBackground(Color.PINK);
        } else {
            txtTitle.setBackground(Color.WHITE);
        }

        if (txtAuthor.getText().trim().isEmpty()) {
            errors.append("• Author is required.\n");
            txtAuthor.setBackground(Color.PINK);
        } else {
            txtAuthor.setBackground(Color.WHITE);
        }

        if (txtPublisher.getText().trim().isEmpty()) {
            errors.append("• Publisher is required.\n");
            txtPublisher.setBackground(Color.PINK);
        } else {
            txtPublisher.setBackground(Color.WHITE);
        }

        // --- Year field ---
        try {
            int year = Integer.parseInt(txtYear.getText().trim());
            txtYear.setBackground(Color.WHITE);
            if (year < 1900 || year > currentYear) {
                errors.append("• Year must be between 1900 and " + currentYear + ".\n");
                txtYear.setBackground(Color.PINK);
            }
        } catch (NumberFormatException e) {
            errors.append("• Year must be a valid number between 1900 and " + currentYear + ".\n");
            txtYear.setBackground(Color.PINK);
        }

        // --- Quantity field ---
        try {
            int quantity = Integer.parseInt(txtQuantity.getText().trim());
            txtQuantity.setBackground(Color.WHITE);
            if (quantity <= 0 || quantity > 1000) {
                errors.append("• Quantity must be between 1 and 1000.\n");
                txtQuantity.setBackground(Color.PINK);
            }
        } catch (NumberFormatException e) {
            errors.append("• Quantity must be a number.\n");
            txtQuantity.setBackground(Color.PINK);
        }

        // --- Combo box (category) ---
        // Recommended: make index 0 a blank like "Select Category"
        boolean comboDefault = cboCategory.getSelectedIndex() == 0;
        if (comboDefault) {
            errors.append("• Please select a category.\n");
            cboCategory.setBackground(Color.PINK);
        } else {
            cboCategory.setBackground(Color.WHITE);
        }

        // --- Price field ---
        String priceText = txtPrice.getText().trim();
        boolean priceInvalid = false;
        try {
            if (priceText.isEmpty()) {
                throw new NumberFormatException("Empty input");
            }

            double price = Double.parseDouble(priceText);
            if (price <= 0.0) {
                priceInvalid = true;
            }
        } catch (NumberFormatException e) {
            priceInvalid = true;
        }

        if (priceInvalid) {
            errors.append("• Price must be a valid positive amount.\n");
            txtPrice.setBackground(Color.PINK);
        } else {
            txtPrice.setBackground(Color.WHITE);
        }

        // --- Show all errors together ---
        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(this,
                    "Please fix the following issues:\n\n" + errors.toString(),
                    "Validation Errors",
                    JOptionPane.WARNING_MESSAGE);

            // Focus on the first invalid field
            if (txtTitle.getBackground() == Color.PINK) {
                txtTitle.requestFocus();
            } else if (txtAuthor.getBackground() == Color.PINK) {
                txtAuthor.requestFocus();
            } else if (txtPublisher.getBackground() == Color.PINK) {
                txtPublisher.requestFocus();
            } else if (txtYear.getBackground() == Color.PINK) {
                txtYear.requestFocus();
            } else if (txtQuantity.getBackground() == Color.PINK) {
                txtQuantity.requestFocus();
            } else if (cboCategory.getBackground() == Color.PINK) {
                cboCategory.requestFocus();
            } else if (txtPrice.getBackground() == Color.PINK) {
                txtPrice.requestFocus();
            }

            return false;
        }

        return true; // all validations passed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scpBook;
    private javax.swing.JTable tblBook;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextArea txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
